/**
 * Nocturn API — main entry point.
 *
 * Exposes `deployNegotiation` and `joinNegotiation` which return a
 * `DeployedNocturnAPI` instance. The API wraps the Compact-generated
 * contract bindings from `managed/negotiation/contract/index.js`.
 *
 * This module is consumed by:
 *   - The React UI (ui/) via WalletContext / NegotiationContext
 *   - The deploy script (scripts/deploy.ts)
 */

import {
  deployContract,
  findDeployedContract,
} from '@midnight-ntwrk/midnight-js-contracts';
import type { ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { combineLatest, map, type Observable } from 'rxjs';
import { createWitnesses, createStubWitnesses, type NegotiationWitnesses } from './witnesses.js';
import {
  decodeStatus,
  type DeployedNocturnAPI,
  type NegotiationState,
} from './types.js';

// ---------------------------------------------------------------------------
// Re-export types so UI only needs to import from @nocturn/api
// ---------------------------------------------------------------------------
export { PREPROD_CONFIG } from './types.js';
export type { DeployedNocturnAPI, NegotiationState, NocturnConfig } from './types.js';
export type { NegotiationWitnesses } from './witnesses.js';
export { createWitnesses, createStubWitnesses } from './witnesses.js';
export { decodeStatus } from './types.js';

// ---------------------------------------------------------------------------
// Compact contract import — resolved after `npm run compile`
// The managed/ directory is generated by `compactc` from negotiation.compact.
// ---------------------------------------------------------------------------

// We use a dynamic import pattern with type assertion because the managed/
// directory may or may not be present depending on compile state.
// In production the contract IS compiled; in CI tests we skip ZK.
async function loadContract() {
  try {
    // This path resolves relative to the workspace root at runtime
    const mod = await import('../../managed/negotiation/contract/index.js' as string);
    return mod;
  } catch {
    // Fallback: return a mock for environments without compiled artifacts
    console.warn(
      '[nocturn/api] managed/negotiation not found — using mock contract.\n' +
        'Run `bash scripts/compile.sh` to generate real artifacts.',
    );
    return null;
  }
}

// ---------------------------------------------------------------------------
// Internal: build the observable state from the contract's public ledger state
// ---------------------------------------------------------------------------

function buildState$(
  contractAddress: ContractAddress,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  contractInstance: any,
): Observable<NegotiationState> {
  return combineLatest([
    contractInstance.negotiationStatus$,
    contractInstance.agreedPrice$,
  ]).pipe(
    map(([{ status, agreedPrice }]) => ({
      status: decodeStatus(status),
      agreedPrice,
      contractAddress: contractInstance.deployedContractAddress,
    })),
  );
}

// ---------------------------------------------------------------------------
// Internal: wrap a deployed contract instance into the DeployedNocturnAPI
// ---------------------------------------------------------------------------

function wrapContract(
  contractAddress: ContractAddress,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  contractInstance: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  providers: any,
): DeployedNocturnAPI {
  const state$ = buildState$(contractAddress, contractInstance);

  return {
    contractAddress,
    state$,

    async openNegotiation() {
      const witnesses = createStubWitnesses();
      const tx = await contractInstance.callTx.openNegotiation(witnesses);
      await providers.walletProvider.submitTx(tx);
    },

    async matchOffer(buyerMax: bigint, sellerMin: bigint) {
      // Witnesses are created here — they exist only for this call's lifetime.
      // buyerMax and sellerMin NEVER appear in the submitted transaction body.
      const witnesses = createWitnesses(buyerMax, sellerMin);
      const tx = await contractInstance.callTx.matchOffer(witnesses);
      await providers.walletProvider.submitTx(tx);
    },
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Deploys a fresh Nocturn negotiation contract and returns the API.
 * Outputs the contract address to the console for inclusion in the README.
 */
export async function deployNegotiation(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  providers: any,
): Promise<DeployedNocturnAPI> {
  const contractMod = await loadContract();
  if (!contractMod) {
    throw new Error('Contract artifacts not found. Run: bash scripts/compile.sh');
  }

  const { Contract, witnesses: defaultWitnesses } = contractMod;

  // @ts-ignore
  const deployed = await deployContract(providers, {
    contract: new Contract(defaultWitnesses ?? createStubWitnesses()),
    privateStateKey: 'nocturn-negotiation',
    initialPrivateState: {},
  } as any);

  const address = deployed.deployTxData.public.contractAddress;
  console.log(`[nocturn] Deployed contract address: ${address}`);

  return wrapContract(address, deployed, providers);
}

/**
 * Connects to an existing Nocturn negotiation contract by address.
 */
export async function joinNegotiation(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  providers: any,
  contractAddress: ContractAddress,
): Promise<DeployedNocturnAPI> {
  const contractMod = await loadContract();
  if (!contractMod) {
    throw new Error('Contract artifacts not found. Run: bash scripts/compile.sh');
  }

  const { Contract } = contractMod;

  // @ts-ignore
  const found = await findDeployedContract(providers, {
    contractAddress,
    contract: new Contract(createStubWitnesses()),
    privateStateKey: 'nocturn-negotiation',
    initialPrivateState: {},
  } as any);

  return wrapContract(contractAddress, found, providers);
}

export * from './types.js';
