/**
 * Nocturn API — main entry point.
 *
 * Exposes `deployNegotiation` and `joinNegotiation` which return a
 * `DeployedNocturnAPI` instance. The API wraps the Compact-generated
 * contract bindings from `managed/negotiation/contract/index.js`.
 *
 * This module is consumed by:
 *   - The React UI (ui/) via WalletContext / NegotiationContext
 *   - The deploy script (scripts/deploy.ts)
 */

import {
  deployContract,
  findDeployedContract,
} from '@midnight-ntwrk/midnight-js-contracts';
import type { ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { map, type Observable } from 'rxjs';
import { createWitnesses, createStubWitnesses, type NegotiationWitnesses } from './witnesses.js';
import {
  decodeStatus,
  type DeployedNocturnAPI,
  type NegotiationState,
} from './types.js';

// ---------------------------------------------------------------------------
// Re-export types so UI only needs to import from @nocturn/api
// ---------------------------------------------------------------------------
export { PREPROD_CONFIG } from './types.js';
export type { DeployedNocturnAPI, NegotiationState, NocturnConfig } from './types.js';
export type { NegotiationWitnesses } from './witnesses.js';
export { createWitnesses, createStubWitnesses } from './witnesses.js';
export { decodeStatus } from './types.js';

// ---------------------------------------------------------------------------
// Compact contract import — resolved after `npm run compile`
// The managed/ directory is generated by `compactc` from negotiation.compact.
// ---------------------------------------------------------------------------

// We use a dynamic import pattern with type assertion because the managed/
// directory may or may not be present depending on compile state.
// In production the contract IS compiled; in CI tests we skip ZK.
async function loadContract() {
  try {
    // This path resolves relative to the workspace root at runtime
    const mod = await import('../../managed/negotiation/contract/index.js' as string);
    return mod;
  } catch {
    // Fallback: return a mock for environments without compiled artifacts
    console.warn(
      '[nocturn/api] managed/negotiation not found — using mock contract.\n' +
        'Run `bash scripts/compile.sh` to generate real artifacts.',
    );
    return null;
  }
}

// ---------------------------------------------------------------------------
// Internal: build the observable state from the contract's public ledger state
//
// The deployed contract from midnight-js-contracts exposes:
//   deployed.callTx.openNegotiation()   — call a circuit
//   deployed.callTx.matchOffer()        — call a circuit
//   deployed.deployTxData.public.contractAddress — the address
//
// To watch contract state changes we subscribe to the publicDataProvider's
// watchForContractState() stream, which emits every time the indexer sees
// the contract state update. We then decode the state using the Compact-
// generated `ledger()` function.
// ---------------------------------------------------------------------------

function buildState$(
  contractAddress: ContractAddress,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  providers: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ledgerFn: (state: any) => { negotiationStatus: bigint; agreedPrice: bigint },
): Observable<NegotiationState> {
  // contractStateObservable streams every ContractState update from the indexer.
  // We use { type: 'latest' } so we immediately get the current state and then
  // receive updates whenever it changes.
  return providers.publicDataProvider
    .contractStateObservable(contractAddress, { type: 'latest' })
    .pipe(
      map((contractState: unknown) => {
        try {
          const decoded = ledgerFn(contractState);
          return {
            status: decodeStatus(decoded.negotiationStatus),
            agreedPrice: decoded.agreedPrice,
            contractAddress,
          } satisfies NegotiationState;
        } catch {
          // Contract state not yet set (e.g. right after deploy before openNegotiation)
          return {
            status: decodeStatus(0n),
            agreedPrice: 0n,
            contractAddress,
          } satisfies NegotiationState;
        }
      }),
    );
}

// ---------------------------------------------------------------------------
// Internal: wrap a deployed FoundContract into the DeployedNocturnAPI
// ---------------------------------------------------------------------------

function wrapContract(
  contractAddress: ContractAddress,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  foundContract: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  providers: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ledgerFn: (state: any) => { negotiationStatus: bigint; agreedPrice: bigint },
): DeployedNocturnAPI {
  const state$ = buildState$(contractAddress, providers, ledgerFn);

  return {
    contractAddress,
    state$,

    async openNegotiation() {
      // callTx.openNegotiation() handles: build tx → ZK prove → balance → submit → confirm
      await foundContract.callTx.openNegotiation();
    },

    async matchOffer(buyerMax: bigint, sellerMin: bigint) {
      // Witnesses are set on the contract instance for this call only.
      // buyerMax and sellerMin NEVER appear in the submitted transaction body.
      foundContract.witnesses = createWitnesses(buyerMax, sellerMin);
      await foundContract.callTx.matchOffer();
      // Reset to stub witnesses immediately after (don't leave private values around)
      foundContract.witnesses = createStubWitnesses();
    },
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Deploys a fresh Nocturn negotiation contract and returns the API.
 * Outputs the contract address to the console for inclusion in the README.
 */
export async function deployNegotiation(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  providers: any,
): Promise<DeployedNocturnAPI> {
  const contractMod = await loadContract();
  if (!contractMod) {
    throw new Error('Contract artifacts not found. Run: bash scripts/compile.sh');
  }

  const { Contract, ledger } = contractMod;

  // Deploy with stub witnesses — the contract constructor doesn't invoke witnesses
  const deployed = await deployContract(providers, {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    compiledContract: new Contract(createStubWitnesses()) as any,
    privateStateId: 'nocturn-negotiation',
    initialPrivateState: {} as never,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any);

  const address = deployed.deployTxData.public.contractAddress;
  console.log(`[nocturn] Deployed contract address: ${address}`);

  return wrapContract(address, deployed, providers, ledger);
}

/**
 * Connects to an existing Nocturn negotiation contract by address.
 */
export async function joinNegotiation(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  providers: any,
  contractAddress: ContractAddress,
): Promise<DeployedNocturnAPI> {
  const contractMod = await loadContract();
  if (!contractMod) {
    throw new Error('Contract artifacts not found. Run: bash scripts/compile.sh');
  }

  const { Contract, ledger } = contractMod;

  const found = await findDeployedContract(providers, {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    compiledContract: new Contract(createStubWitnesses()) as any,
    contractAddress,
    privateStateId: 'nocturn-negotiation',
    initialPrivateState: {} as never,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any);

  return wrapContract(contractAddress, found, providers, ledger);
}

export * from './types.js';
